---
apiVersion: v1
kind: Namespace
metadata:
  name: valheim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim
  namespace: valheim
spec:
  selector:
    matchLabels:
      app: valheim
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: valheim
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: valheim
      initContainers:
        - name: steamcmd
          image: steamcmd/steamcmd
          command:
            - steamcmd 
            - +@sSteamCmdForcePlatformType 
            - linux 
            - +force_install_dir 
            - /data 
            - +login 
            - anonymous 
            - +app_update 
            - '896660' 
            - -beta 
            - none 
            - validate 
            - +quit
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
      - name: valheim
        image: steamcmd/steamcmd
        command:
          - ./valheim_server.x86_64
          - -name
          - Jörmungandr
          - -port
          - '2456'
          - -nographics
          - -batchmode
          - -world
          - world
          - -password
          - SubmitToTheCult 
          - -public 
          - '1'
        workingDir: /data
        env:
          - name: LD_LIBRARY_PATH
            value: /data/linux64
          - name: TERM
            value: xterm
          - name: SteamAppID
            value: '892970'
        resources:
          limits:
            memory: "3500Mi"
            cpu: "3000m"
          requests:
            memory: "2500Mi"
            cpu: "300m"
        volumeMounts:
          - mountPath: /data
            name: data
        ports:
        - containerPort: 2456
          protocol: UDP
        - containerPort: 2457
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: valheim
  namespace: valheim
spec:
  selector:
    app: valheim
  type: NodePort
  ports:
  - name: port-2456-udp
    port: 2456
    targetPort: 2456
    nodePort: 32456
    protocol: UDP
  - name: port-2457-udp
    port: 2457
    targetPort: 2457
    nodePort: 32457
    protocol: UDP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim
  namespace: valheim
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
