---
apiVersion: v1
kind: Namespace
metadata:
  name: moths-domain
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: moths-domain
  namespace: moths-domain
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: mc
        namespace: default
  values:
    replicaCount: 1
    minecraftServer:
      eula: "TRUE"
      type: PAPER
      version: 1.20.4
      memory: 2500M
    resources:
      requests: 
        memory: 2Gi
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "moths-domain.izzy.kiwi"
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
  interval: 5m0s
