apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: ingress
spec:
  interval: 5m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: ingress
spec:
  chart:
    spec:
      chart: cert-manager
      version: '1.17.2' # v1.18 has an issue with ingress-nginx: https://github.com/cert-manager/cert-manager/issues/7791
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: http-issuer
  interval: 5m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
# This depends on ingress release. If deploying from scratch, remove this, deploy, add it back, deploy. 
# I feel like Flux has a way to fix this but I don't know it
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
