apiVersion: v1
kind: Secret
metadata:
    name: route53-credentials
    namespace: ingress
stringData:
    access-key-id: ENC[AES256_GCM,data:VXLJ4XyrbOe4hTsSqU5gsv1EL/Y=,iv:HF0dSYbKy5l/HRg70ICMDEzy3SLeZQ8kRpyXsIBGJmQ=,tag:dlpuJ4euzuX4NU0xmy7r5Q==,type:str]
    secret-access-key: ENC[AES256_GCM,data:/Rwir0L7Bep1dnYb6XJakLDBxzmswQVQeQg/5oLWiuH3pdx+1qUpMQ==,iv:9DaDkNQGE7jiiV3sqRNvMQiOy5lw7ulv8kBfQoET4ws=,tag:oaofXykv3dUmOQHhL/b69w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Q2dVRG8rR0YyUnlKMzFX
            dDIzM0tTQTBEazhzV3hwd1FRRjI3bER3WVhJCmdieEJrNlBLSkIwQ0pNOEtOTStF
            N21EeGJtSEVJUWJ3M1ptVEthYkV5eVkKLS0tIG9VVzdDQ3BacnFtN1IzYTdKRG1U
            T0Q0MzdPR0xnVVVYWjVtOFI4VXdndWsKFYySzfbM6MXO/QFDSMwkj6A9Qn6byUIx
            1+DGAujmmo7ShoRQ8WealR1HSeVQyqVperWPmqXon2hLXZdc+w9hSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T04:31:54Z"
    mac: ENC[AES256_GCM,data:InEtUl00NQjTCIUjU1jr+hBcxVJ+pR+nw+hFeZWbKRqZlOzCOv/zCQJMZo1oi/ythRW1vdk4BPMcQ28Rlhrgqy1CvOats5Ec44O+9XbcGIbHNTQd8WZ9XDxQfhPpf3+CAGScDiv4c0gbssgTABCMh0XrN8Mfh7ZcLGiDI/4JRVE=,iv:B7XLB0UZSA0Y7hBiixFno86ayb0/IJpfPJ6mi+ud3X8=,tag:gGPEvoKz2KO8TK/k3ouabw==,type:str]
    version: 3.13.1
