apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwn2own-ghidra
  namespace: pwn2own-ghidra
  labels:
    app: pwn2own-ghidra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pwn2own-ghidra
  template:
    metadata:
      labels:
        app: pwn2own-ghidra
    spec:
      containers:
        - name: ghidra-server
          image: "blacktop/ghidra"
          args:
            - "server"
          env:
            - name: GHIDRA_USERS
              value: "admin ttrss smallpenisbig"
            - name: GHIDRA_PUBLIC_HOSTNAME
              value: "192.168.100.210"
          volumeMounts:
            - name: ghidra-repos
              mountPath: /repos
          ports:
            - containerPort: 13100
              protocol: TCP
            - containerPort: 13101
              protocol: TCP
            - containerPort: 13102
              protocol: TCP
      volumes:
        - name: ghidra-repos
          persistentVolumeClaim:
            claimName: ghidra-repos
