apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwn2own-ghidra
  namespace: pwn2own-ghidra
  labels:
    app: pwn2own-ghidra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwn2own-ghidra
  template:
    metadata:
      labels:
        app: pwn2own-ghidra
    spec:
      containers:
        - name: proxy-30690
          image: alpine/socat:latest
          args: 
            - "TCP-LISTEN:30690,fork,reuseaddr"
            - "TCP:127.0.0.1:13100"
          ports:
            - containerPort: 30690
        - name: proxy-30691
          image: alpine/socat:latest
          args: 
            - "TCP-LISTEN:30691,fork,reuseaddr"
            - "TCP:127.0.0.1:13101"
          ports:
            - containerPort: 30691
              protocol: TCP
        - name: proxy-30692
          image: alpine/socat:latest
          args: 
            - "TCP-LISTEN:30692,fork,reuseaddr"
            - "TCP:127.0.0.1:13102"
          ports:
            - containerPort: 30692
              protocol: TCP
        - name: pwn2own-ghidra-server
          image: "bytehow/ghidra-server"
          env:
            - name: GHIDRA_USERS
              value: "admin ttrss smallpenisbig"
            - name: GHIDRA_PUBLIC_HOSTNAME
              value: "0.0.0.0"
          volumeMounts:
            - name: ghidra-repos
              mountPath: /repos
      volumes:
        - name: ghidra-repos
          persistentVolumeClaim:
            claimName: ghidra-repos
