apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwn2own-ghidra
  namespace: pwn2own-ghidra
  labels:
    app: pwn2own-ghidra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pwn2own-ghidra
  template:
    metadata:
      labels:
        app: pwn2own-ghidra
    spec:
      containers:
        # - name: proxy-30690
        #   image: alpine/socat:latest
        #   args: 
        #     - "TCP-LISTEN:30690,fork,reuseaddr"
        #     - "TCP:127.0.0.1:13100"
        #   ports:
        #     - containerPort: 30690
        # - name: proxy-30691
        #   image: alpine/socat:latest
        #   args: 
        #     - "TCP-LISTEN:30691,fork,reuseaddr"
        #     - "TCP:127.0.0.1:13101"
        #   ports:
        #     - containerPort: 30691
        #       protocol: TCP
        # - name: proxy-30692
        #   image: alpine/socat:latest
        #   args: 
        #     - "TCP-LISTEN:30692,fork,reuseaddr"
        #     - "TCP:127.0.0.1:13102"
        #   ports:
        #     - containerPort: 30692
        #       protocol: TCP
        - name: pwn2own-ghidra-server
          image: "bytehow/ghidra-server"
          command:
            - bash
            - -c
            - apt-get update; apt-get install iproute2 -y; GHIDRA_PUBLIC_HOSTNAME=$(ip a show dev eth0 | egrep -w inet | egrep -o "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | head -1) /entrypoint.sh server
          env:
            - name: GHIDRA_USERS
              value: "admin ttrss smallpenisbig"
          volumeMounts:
            - name: ghidra-repos
              mountPath: /repos
          ports:
            - containerPort: 30690
              protocol: TCP
            - containerPort: 30691
              protocol: TCP
            - containerPort: 30692
              protocol: TCP
      volumes:
        - name: ghidra-repos
          persistentVolumeClaim:
            claimName: ghidra-repos
