apiVersion: v1
kind: Service
metadata:
  namespace: pwn2own-ghidra
  name: pwn2own-ghidra
  labels:
    app: pwn2own-ghidra
spec:
  ports:
    - port: 13100
      targetPort: rmi
      protocol: TCP
      name: rmi
  clusterIP: None
  selector:
    app: pwn2own-ghidra
