apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  chart:
    spec:
      chart: qbittorrent
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  values:
    ingress:
      main:
        hosts:
          - host: qbittorrent.izzy.kiwi
        tls:
         - secretName: qbittorrent-tls
           hosts:
             - qbittorrent.izzy.kiwi
