---
apiVersion: v1
kind: Namespace
metadata:
  name: flatcraft
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flatcraft2
  namespace: flatcraft
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    replicaCount: 1
    minecraftServer:
      eula: "TRUE"
      type: FABRIC
      version: 1.21.10
      memory: 2500M
      motd: flatcraft
      levelType: FLAT
      modrinth:
        projects: [worldedit, axiom, fabric-api]
        allowedVersionType: beta
      ops: boxhead_crafter,OscarE2903,pickettpastries
      gameMode: creative
    resources:
      requests: 
        memory: 2Gi
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "flatcraft.cult-flat.izzy.kiwi"
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
  interval: 5m0s