apiVersion: v1
kind: Namespace
metadata:
  name: streamio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamio
  namespace: streamio
  labels:
    app: streamio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamio
  template:
    metadata:
      labels:
        app: streamio
    spec:
      containers:
        - name: streamio
          image: stremio/server
          env:
            - name: NO_CORS
              value: "1"
          ports:
            - containerPort: 11470
              protocol: TCP
          resources:
            requests:
              memory: 150Mi
---
apiVersion: v1
kind: Service
metadata:
  name: streamio
  namespace: streamio
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: streamio
  ports:
    - protocol: TCP
      port: 11470
      targetPort: 11470
