apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argo-helm
  namespace: argo-cd
spec:
  interval: 5m0s
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-helm
  interval: 5m0s
  values:
    global:
      domain: argocd.izzy.kiwi
    configs:
      cm:
        admin.enabled: false
        oidc.config: |
          name: AzureAD
          issuer: https://login.microsoftonline.com/0d9b6779-97c8-4804-83d4-596403a3aedf/v2.0
          clientID: d86cdc4e-da9b-4ccd-8a6c-6acb6a3e0728
          clientSecret: $oidc.azuread.clientSecret
          requestedIDTokenClaims:
            groups:
              essential: true
          requestedScopes:
            - openid
            - profile
            - email
      params:
        server.insecure: true
      rbac:
        policy.default: 'role:org-admin' # If you're in my Entra ID, I trust you
        policy.csv: |
          p, role:org-admin, applications, *, */*, allow
          p, role:org-admin, clusters, get, *, allow
          p, role:org-admin, repositories, *, *, allow
          p, role:org-admin, logs, get, *, allow
          p, role:org-admin, exec, create, */*, allow
      secret:
        createSecret: false
    controller:
      metrics:
        enabled: false # TODO
    dex:
      enabled: false
    redis:
      exporter:
        enabled: false # TODO
    server:
      metrics:
        enabled: false # TODO
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: http-issuer
          nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
          nginx.ingress.kubernetes.io/auth-tls-secret: default/ca-secret
          nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
          nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
        tls: true
    repoServer:
      metrics:
        enabled: false # TODO
    applicationSet:
      metrics:
        enabled: false # TODO
      ingress:
        enabled: true
        tls: true
        annotations:
          cert-manager.io/cluster-issuer: http-issuer
    notifications:
      ingress:
        enabled: true
      notifiers: {} # TODO
      triggers: {} # TODO
      
        
    

