apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argo-cd
type: Opaque
stringData:
    server.secretkey: ENC[AES256_GCM,data:jEEUk1+cUY5SU7pROgBK26MNIpc5C1h4wHbAkV/hkMc=,iv:wNLZM+0ZRZWWIcpDjIPSKnpb439ELslxOHXGtrsfMwE=,tag:AIOJcyfIoHpRmjCSEvkufg==,type:str]
    oidc.azuread.clientSecret: ENC[AES256_GCM,data:Hfk8Uz8GcvBVDczP/OfYDZX7T3vuyuyieSf+yaEly7rIiL2SUda5rA==,iv:d7CuXYQtbSehrE6LmUhwfEYWUT2l7wWNYOrjp5VZf5Q=,tag:hTKISh8Yd7TAfKmtoHrW1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTTBSV0c0YXd3NGlTekhu
            RG9UVjU5R3JWWmcwaVd3c3BIUGJsR1ZmVmlzCk5YMS9CMC9IVU5FZzcrcTRXckZQ
            c0Y4aFZmYldZNStLMDdIZExFSm1FOUUKLS0tIG5KWmh6V1MvQi9UTkk5RVlLK2Vz
            TkhCTWVIaDBqeW55Y0V6eURWRFRFc1kK0C7wEtaaPsw/uGjQtog1NneTgPLFDrcJ
            fEPdwMhF+Ab3+DCXueKBjpmw1WrncvvkhYNsdSxzVTprVFOZVF1/Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T08:25:53Z"
    mac: ENC[AES256_GCM,data:rzcTN0kS7lSSstR+GI3rp9AQgjNBsoLRCk69gNqxGrOwdEz15vieP/nEvf8kDwjOiYW2YK8TukrHZstVRBmnHv3AH2xRXRaimUp2WPo0yzjLd/lfygGh+rsZUN8m44e24he+gtlWocXYr1Z/MSHhl8Fm8+MMiBsZT6FMrHVGBvA=,iv:SLYbRQ4LHGjb3T2y0ipcXfwanL1sVc4RVBZVkzIZHCQ=,tag:zbFeyAxXlDQktDW8XoMS1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
