namespace: odin-2
resources:
  - namespace.yaml
  - ../../../bases/odin-2
secretGenerator:
  - name: postgres
    envs:
      - postgres.sops.env
  - name: regcred
    envs:
      - regcred.sops.env
    type: kubernetes.io/dockerconfigjson
images:
  - name: ghcr.io/tomay0/odincards
    newTag: 2025-01-27t10-37-49
