namespace: odin-2
resources:
  - namespace.yaml
  - ../../../bases/odin-2
secretGenerator:
  - name: postgres
    envs:
      - postgres.sops.env
  - name: regcred
    envs:
      - regcred.sops.env
    type: kubernetes.io/dockerconfigjson