---
apiVersion: v1
kind: Namespace
metadata:
  name: rizzcraft
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rizzcraft
  namespace: rizzcraft
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    minecraftServer:
      eula: "TRUE"
      type: VANILLA
      version: 1.21.5
      memory: 2000M
      ops: boxhead_crafter,HighCarbon
      motd: "RIIIIIIIIIIZZZZZZZZZZZZZZzzzzzzzzz........"
    resources:
      requests:
        memory: 2500Mi
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "rizzcraft.izzy.kiwi"
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
  interval: 5m0s
