apiVersion: v1
kind: Pod
metadata:
  name: pvc-setup
spec:
  containers:
  - name: setup
    image: ubuntu
    command: ['sleep', 'inf']
    volumeMounts:
    - name: vol
      mountPath: /data
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: name-minecraft-datadir
