apiVersion: v1
kind: Secret
metadata:
    name: ddns-aws
    namespace: ddns
stringData:
    access-key-id: ENC[AES256_GCM,data:RqAeL7S5PWOzclpkRd6wIlMBSGM=,iv:LDY/MZN15TOEw5x+QxP1dbo3hm6uVkEyuj+3ap29Iro=,tag:5SvFtwXMzGqwdI7/aySjLw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:XtIjgZmnmRTI4s3Bg55PdGeLIV9LOpiilvkgRN6az50z9QHTZ3Bnqg==,iv:zm0c6dpecH4lSQMWcLb0PnkQOnSQgIJY6Vm231t1gl8=,tag:bCsy7m885cfGskCufO/laQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeXJsUml5TkRMa2NmczJB
            Q2VPWkxaamEybFVDelI2dnFkVCt4aXNuUWswCjQrT2hnYjMvV1JrNXVzV1pwbHM1
            c2luVGlUQ01NUVhhQ0IweXVrN0R6QWsKLS0tIHZwbk5URngwM29hM2Rsd0VWeFBZ
            T0JLQ3VoS1FSSmNxZUk2V3BPUUlLWncK9Kjfvx77RmxC+SqTMYPomXCzr++zFSpK
            iCD7RL27PcMEZNyNr8ul6sInzRouT6xu2+qLSccr5rD+JTkKaNr5Qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T05:08:30Z"
    mac: ENC[AES256_GCM,data:FEQgxbUlZULKoWJ8dr6jUB56jxQvt3ZcZUHKE8y5fTJwTZ6SbbDVCznpVBZjat5JU1DJnUWgpSB369XrzuzBf2L23RlD/mHd8MC21vOoxhzhloanjlF/gOwMOxXpt5rnNk1UZ8dLzrCOhzs8BdoYzB875/KMGj6ukPozrufBLJo=,iv:/hhOL4WdFmOQNyIW+XuWXWTLoMRLlliZ4znLyIbNBvQ=,tag:+a1Vcro6BhNaLYh7atbWuA==,type:str]
    version: 3.13.1
