apiVersion: v1
kind: Secret
metadata:
    name: palworld-passwords
    namespace: palworld
stringData:
    server-password: ENC[AES256_GCM,data:Qi/3u2MVkMkQh47O9iI=,iv:fnFal/hVzFJf+gRMOgGYSGWMe9b9m6piLdEMqsCVoMo=,tag:7fbVFnkYxOLOOuiIDKTpTQ==,type:str]
    admin-password: ENC[AES256_GCM,data:70vHf9/iz1w3OTHD47QxMa3R4CaeNVll,iv:NJ2iLhRfS++zLjhK+agEkUXOqHuRXZDUI10L8yi53VA=,tag:EEUHLppgQJoF20jgd50JaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdWxFdmVVUjIyLzdSbzdF
            cTZ2K0dRTVJIV0I0c3BlU1Y3Z3ZpZW1iMHdRCmcwZnA3emM1M1hUMTFEZm9jaFNV
            eHFLVmRtTmZaTHVNWEFUaTd1UWxpOG8KLS0tIDJzVTA2R0JlRTNhclVURDBHNkVD
            STJDa0JRZnlvUTJhUlR4b1QyOFhyS1kKm3rLTg8ENvjt/jwDfO/muUlHrB3a7WlI
            vaXCX7EOvHISUoe0stcAJ7Ru6tAzSjkZBKhTlDqdVf/LpPag3XIr1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T07:23:51Z"
    mac: ENC[AES256_GCM,data:xIEy+TEBokskM74nVguQXqs6liyfMuolOmnP42jGEbHdTSfwesJ7XuxZvkXh98nk3ugGTmzoeoB5BLLBQKrr5tNyZfqNWEyM62zeZC2sQOAYU0nokmzp/l35gpRlIcrMn+DNhT//YXM6WNL0m0iN6jZthcoYwTIr6Akl1dD77v4=,iv:2A0XdZ+JOXDLiyvNV3tMjdOy3SfZ+wE5CXyEZDOJ3p0=,tag:Km6YkaVLAOUMI5UBGkVH1Q==,type:str]
    version: 3.13.1
