apiVersion: v1
kind: Service
metadata:
  name: mc-servicey
  namespace: aa-cup
  annotations:
    "mc-router.itzg.me/externalServerName": "aa-cup.xeraxera.me"
spec:
  selector:
    app: minecrafty
  ports:
    - port: 25565
      targetPort: 25565
