apiVersion: v1
kind: Namespace
metadata:
  name: iperf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf
  namespace: iperf
spec:
  selector:
    matchLabels:
      app: iperf
  template:
    metadata:
      labels:
        app: iperf
    spec:
      containers:
      - name: iperf
        image: networkstatic/iperf3
        command:
          - -s
        ports:
        - containerPort: 5201
---
---
apiVersion: v1
kind: Service
metadata:
  name: iperf
  namespace: iperf
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.214
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: iperf
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
