apiVersion: apps/v1
kind: Deployment
metadata:
  name: saggy-mc
  namespace: saggy-mc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: saggy-mc
  template:
    metadata:
      labels:
        app: saggy-mc
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        runAsNonRoot: true
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mc
          securityContext:
            capabilities:
              drop:
                - ALL
            # readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          image: itzg/minecraft-server
          volumeMounts:
            # - name: data
            #   mountPath: /data
            - name: tmp
              mountPath: /tmp
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: 2G
            - name: RCON_HOST
              value: "localhost"
          resources:
            requests:
              cpu: 150m
              memory: 2500M
          livenessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            exec:
              command:
                - mc-health
            enabled: false
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: saggy-mc
        - name: tmp
          emptyDir: {}
