apiVersion: apps/v1
kind: Deployment
metadata:
  name: saggy-mc
  namespace: saggy-mc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: saggy-mc
  template:
    metadata:
      labels:
        app: saggy-mc
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - name: mc
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          image: itzg/minecraft-server
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: 2G
            - name: RCON_HOST
              value: "localhost"
          resources:
            requests:
              cpu: 150m
              memory: 2500M
          livenessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 120
            periodSeconds: 60
          readinessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: saggy-mc
