apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saggy-mc
  namespace: saggy-mc
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-rbd-sc-retain
