apiVersion: v1
kind: Service
metadata:
  name: mc-router
  namespace: mc-router
spec:
  type: NodePort
  ports:
  - targetPort: proxy
    name: proxy
    port: 25565
    nodePort: 32565
  selector:
    run: mc-router
