apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: zfs
spec:
  nodeName: leo
  containers:
  - image: ubuntu
    command:
      - sleep
      - inf
    name: shell
    resources: {}
    securityContext:
      privileged: true