apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: zfs
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeName: leo
      containers:
      - image: ubuntu
        command:
        - /bin/bash
        - -c
        - |
          apt update
          apt install -y ssh
          sleep inf
        name: shell
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
          - name: ssh-key
            mountPath: /root/.ssh
            readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key
