apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-bot
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-bot
  namespace: flux-system
spec:
  providerRef:
    name: discord-bot
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: '*'
    - kind: Kustomization
      name: '*'
      namespace: '*'
