apiVersion: v1
kind: Service
metadata:
  name: beans-old-domain
  namespace: beans
  annotations:
    mc-router.itzg.me/externalServerName: test.beans.isaacirvine.me
spec:
  ports:
    - name: mc
      protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app.kubernetes.io/instance: beans
    app.kubernetes.io/name: beans
