apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: uwu-co-nz
  namespace: uwu-co-nz
spec:
  image: ghcr.io/ttrssreal/uwu-co-nz
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: uwu-co-nz
  namespace: uwu-co-nz
spec:
  imageRepositoryRef:
    name: uwu-co-nz
  policy:
    numerical:
      order: asc

