# TODO:
#  - Oauth
#  - PVC

---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: pajikos
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: http-issuer
        nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
        nginx.ingress.kubernetes.io/auth-tls-secret: default/ca-secret
        nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
        nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
      hosts:
        - host: home-assistant.cult-flat.izzy.kiwi
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: home-assistant-tls
          hosts:
            - home-assistant.cult-flat.izzy.kiwi
  interval: 10m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pajikos
  namespace: home-assistant
spec:
  interval: 10m0s
  url: https://pajikos.github.io/home-assistant-helm-chart/
