---
apiVersion: v1
kind: Namespace
metadata:
  name: fuck-izzy
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: website
  namespace: fuck-izzy
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
  values:
    ingress:
      enabled: true
      hostname: fuck.izzy.kiwi
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: http-issuer
    service:
      type: ClusterIP
    staticSiteConfigmap: www
  interval: 5m0s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: www
  namespace: fuck-izzy
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Application to fuck izzy :3</title>
      </head>
      <body style="background: pink;">
        <iframe 
          src="https://docs.google.com/forms/d/e/1FAIpQLSdyL8VSixaA6sEq59IxglrCHBAE7_pdsKnEMFmQIEh9GqjlOA/viewform?embedded=true" 
          width="100%" 
          height="1000px"
          frameborder="0"
          marginheight="0"
          marginwidth="0"
        >
          Loading…
        </iframe>
      </body>
    </html>