namespace: global-game-jam-2025
resources:
  - namespace.yaml
  - ../../../bases/game-jam-runner
secretGenerator:
  - name: runner-token
    envs:
      - runner.sops.env
patches:
  - target:
      kind: Deployment
      name: game-jam-runner
    patch: |
      - op: replace
        path: /spec/template/spec/initContainers/0/env/0/value
        value: https://github.com/Izzy-Irvine/global-game-jam-2025
  - target:
      kind: Ingress
      name: game-jam-runner
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: global-jam-25.izzy.kiwi
      - op: replace
        path: /spec/rules/host
        value: global-jam-25.izzy.kiwi
   