namespace: global-game-jam-2025
resources:
  - namespace.yaml
  - ../../../bases/game-jam-runner
secretGenerator:
  - name: runner-token
    envs:
      - runner.sops.env
patches:
  - target:
      kind: Deployment
      name: game-jam-runner
    patch: |
      - op: replace
        path: /spec/template/spec/initContainers/0/env/0/value
        value: https://github.com/Izzy-Irvine/global-game-jam-2025
   