apiVersion: v1
kind: Service
metadata:
  name: mc-servicey
  namespace: ava-mc
  annotations:
    "mc-router.itzg.me/externalServerName": "ava-mc.xeraxera.me"
spec:
  selector:
    app: minecrafty
  ports:
    - port: 25565
      targetPort: 25565
