# Run 'talhelper genconfig -s talsecret.sops.yaml' to turn this into talos config

---
clusterName: clowder
talosVersion: v1.9.5
kubernetesVersion: v1.32.3
endpoint: https://192.168.100.200:6443
nodes:
  - hostname: algernon
    ipAddress: 192.168.100.201
    controlPlane: true
    machineDisks:
      - device: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S4EWNM0W355680K
        partitions:
          - mountpoint: /var/lib/longhorn
    nodeLabels:
      node.longhorn.io/create-default-disk: "true"
    installDisk: /dev/sdb
    networkInterfaces:
    - interface: eno1
      vip: 
        ip: 192.168.100.200
    patches:
    - |-
      - op: add
        path: /machine/kubelet/extraMounts
        value:
          - destination: /var/lib/longhorn
            type: bind
            source: /var/lib/longhorn
            options:
              - bind
              - rshared
              - rw
  - hostname: rusty
    ipAddress: 192.168.100.202
    controlPlane: true
    installDisk: /dev/sdb
    nodeLabels:
      node.longhorn.io/create-default-disk: "true"
    machineDisks:
      - device: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S4EWNM0W347804K
        partitions:
          - mountpoint: /var/lib/longhorn
    networkInterfaces:
    - interface: eno1
      vip: 
        ip: 192.168.100.200
    patches:
    - |-
      - op: add
        path: /machine/kubelet/extraMounts
        value:
          - destination: /var/lib/longhorn
            type: bind
            source: /var/lib/longhorn
            options:
              - bind
              - rshared
              - rw
  - hostname: leo
    ipAddress: 192.168.100.203
    controlPlane: true
    installDisk: /dev/sdb
    networkInterfaces:
    - interface: eno1
      vip: 
        ip: 192.168.100.200
    kernelModules:
      - name: zfs
allowSchedulingOnControlPlanes: true
controlPlane:
  nodeLabels: {}
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/zfs
patches:
  - |-
    - op: add
      path: /cluster/proxy/extraArgs
      value: 
        metrics-bind-address: 0.0.0.0:10249
    - op: add
      path: /cluster/controllerManager/extraArgs
      value: 
        bind-address: 0.0.0.0
    - op: add
      path: /cluster/scheduler/extraArgs
      value: 
        bind-address: 0.0.0.0
