apiVersion: v1
kind: Secret
metadata:
    name: immich-migrate
    namespace: immich
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:X4vUmgVER24AoyPdyWueacWizmSLfRaYzkdjObwnLQHTWVUCe9D2vzQ=,iv:F2cWAmxxiy5I3OeMXt61r2tQ07+GQi396QfVgVhpSrI=,tag:GtSmXZwCm7/50B7a+m8jrw==,type:str]
    rclone.conf: ENC[AES256_GCM,data:MIq6DT6BoLwWevuDTu80JeJNM21l3BIHO1UHHqa9PNvverKIGe22H91OQSUzNTWlThBZloZCpdKwHX/6kHMiJBIhwHwDszBLfH8UQzA8X9verROOW2UU/R+YABvD0qYD5Mz3d4gbAcEbpM6pcyRpE7cPlJn5eCnDWNxw37spUZRR9ZHjLQgd0oo4Ty5h9wXkUmSMgno9I9J5BovJjyhYC6CFEdWuRIxVsYJgkKy3g7S514l6DbepXsMK5EytbxF/lUixwKxjWH1Md9Qv1IGv3GmJFTKv1fMK75RQhPRWV6M4rTAOJJbC2iKwsWl34szLa2BtPpqVXLoW3zeR3iR8votuYOX3GclY1FWy1PBu7jq4V238u+uE7QsVJS879KKBD4ycNvnhExp4aOvNRAVYk1ZyjGz5WUC83/zIYCOMrQffpLxRBZjrlSroLtg6FNCl4uFpPGAdufzC3VJf4kYmd9xHPGA05xeQRNuBLCWwfiORcKQeg20EqjDuM6yZROYVA8gSltxgAtkg9YA6N0sohdyCfaC4CLoN/pYKRQyy51F8AfGSVT3LX6gKkxw8WtbMwT2D37gVBVmJbyhlQe99S8xkznYkKwgmYNgpcBUhoosGgBu/GglKC6LNpT5114M6oFXCMOkUIskRK3b33aZIzDtIaXwqeDp5GK0keLDM+BMBlJO6TstnCyK/jSuLJxm8LAIGUS+4XzaAEdVDoUuBVSQVv6EHWS1ziLuao2SxoSH2uUkXWrQRtSOTKU09tOkldXBUQoVTgRVisCrNaSIcMZ557e2Sq7Ki4JYUpEMlIIlzrdaw2waPre5S4n2ctKC4gm3ZkFqwFpDzMtvSsijJrOSa7yARWppsOHbmZyi1wJrCJiWnzzieXdY19uvyw4mEGAC5cAsubtYx0cLQ,iv:FdJG59vb/vZpymtOZgHhtJJ4Sgo9cMYYpUZtmvbVfeg=,tag:Gk5VzI1OTtUCSlgKlwuy5Q==,type:str]
    drive-path: ENC[AES256_GCM,data:fcTu9d56OZqgW//r/iM=,iv:9lfZC0ooVOuFJHdnS4p28qzJcN3Q5cy8cCqdc4xgti8=,tag:P1wXnhYpJW+PMMxVjpAa4Q==,type:str]
sops:
    age:
        - recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NzU2bk5nUDk3Z0ozdnd3
            YlBwR1dneWZKWWIwazJMdEl2emRadTU5cTNJCm5QZnQweldsaXhKaTBaY2RTZHlv
            OTRYdmJXK1h0NEczcUNoYmtMa3E3ZUUKLS0tIFNvQU9wWXVsd0VBQVVXdktkbEl5
            VEZPTHJhTTh4MnRmdVRvOE9PUGR0d00KTSxeKpobKj83aNXuKdb2zOMmqArRGDOK
            Srb5Nfl9cG3H9oZ5JtkJKG8m1iafTyLUZmzh9wz6L53C88d7OZ2eeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T09:00:23Z"
    mac: ENC[AES256_GCM,data:Z0yREEsdCk8oPQhLQbejEILt8cP3gFYl50vlh4vOMxZUyQUVfvQnnk2e1P6G2abLgzVyoGbWfgpcNDdHop3GLfNQoqxeO0lPAKnmmbsvVWJp173P1enNR0H02EchoBCq729yawsKpO8DCqRk3SyV505kjutpcHyKgyfM+AQtX84=,iv:SFxPATzj3uMReETGJ0kotjZU/vfrsbVe1Q6a8eQaiQo=,tag:EDl/YuKIaidNbGd5Wm21sA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
