apiVersion: v1
kind: Secret
metadata:
    name: immich-migrate
    namespace: immich
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:goYBoG9nbDEcxrOqZ3B3UDlXnm44iN960syuB6gHuCyEv5zTcx7xo2c=,iv:dc/t4/Lh9w7wg4AMT3fzva/rL25Ld8wtoKJ8pBAL5g8=,tag:WUBg6+4yzrFIt7TqQeTr2A==,type:str]
    rclone.conf: ENC[AES256_GCM,data:f4RMdtAACy8SQAu/JcNifHQgZEM09Nh7nebmLHGccChKqkFywS3ppM8o0Uk1aV87VAjdjFNLmXsdbD1s1FfggdiIJgchA+r+MmawZo9RRBziiXvKWbblcS2L,iv:6bW8qTXAYpG+ngxBoh0gwQw1A5hLoUkQP10FrXKG3Zo=,tag:98kam1loOr8HSC1CeiVtXQ==,type:str]
    drive-path: ENC[AES256_GCM,data:wCkWbdaS+MjdFVWdNS0=,iv:ctXZ+m60V6YNz+jscPTUCVTN1zcZBbd9nksIlRMv2K0=,tag:RqrtKsMsZsXHKpXG/EgYVg==,type:str]
sops:
    age:
        - recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYndBUlk2SW5VQmZRUUYw
            c2hKWFgzTWNydjZJQVU1SmVramZFNmVJWWxZClRBS0pVbXFsb1V0YkVwcndBZzRT
            NEprQ1IzaG40Z3Z6Z2dKaGV2MmF5c0EKLS0tIGdvdnhNd241ZDVtdk91cS83Zk9r
            OWhJYUxiWlFhTDh6K0xhZjFjVkt3RmsKPeyY5RlXqO8t9+DUbxBc42XUTW7Epjb8
            f3hwfJsHvOS8ISu/IjSJcFrqfET+aS5yrkKfcQfq/LXLWXCiSQdFdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T05:20:34Z"
    mac: ENC[AES256_GCM,data:Fa0FGM2uk+bB3sUFxrq/NWBoua3jHR5YR2YpaTJifInIDqaek7eI6E/vXv+S7F8eQO1yojaNLea2qnmKyv8ztdZORTnDmhBaJXmZ8Nz36vBb9URnJteEkCT5JYQC0g4zg9Jgtr32J4R+3KjuGnbTCkz7MH/tq1eUu1IEzklNlDo=,iv:Oj+DAJ+66dddAKzr7Qgxxdmu28NO/Oewu4cjNgSZfak=,tag:/yT+J0KiOPmApAGZkR1UHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
