apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:PjvHLWiJcYFCHxGT3Foy4ZB4ePrAPPkKq2ycSJ3KaPZScoGcl4u6vlmTtc6HZKsD,iv:pIYTfSiRDASY2FXQ9M2hXxI3P3LiMPlgS+/YxiKwg0Q=,tag:9bKAF6sRNCugGnZ5CTgR0w==,type:str]
sops:
    age:
        - recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUlJUOGNOckxOdjJGaHJL
            VHlGa3l4VE44ZDk1LzlrOUtjUG5ycUFDT0NjCk1yektMaGYxM0hOSFNtK1ZJTGg0
            QkNkaXNHblRHL0tiZkFnY0FzcG5hWEUKLS0tIHgvTUVENzNNSWIrYXliMmI2R20r
            bmpQczMxUzZIZ1dzL2xrSEJ0a3RJMWMKxcs7zRVWiPOdFSr/TPCAT5ahNfrFQBmB
            qQhITOCIQyw5Mzr1yzpWJuDf4OXJyL8f0QuFsTSHIk/vC5wZfj3TsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T08:42:33Z"
    mac: ENC[AES256_GCM,data:uWCQEhY88ysguwPQ7N6qkQDqtopSoSNJCEdkAsNKrjIXjY+GUicloK7XMSsGgqijP/WBtTZaZLEoQCe9acJxcmt2/inmkk51VzHxMSGi3T/yTvExqrBLuYh0Sdaq9HnE+MHuu4dlKil9203RIuwTPKsn/rQ2JUruo3gXBr7bX/0=,iv:5XRixgPnozW/WntqKP5/EXqfvNc9IHBR2JCtf/FWemI=,tag:l1c8CEVb9ct/DWsvok8lSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
