namespace: odin-2
resources:
  - namespace.yaml
  - ../../../bases/odin-2
secretGenerator:
  - name: odin
    envs:
      - odin.sops.env
  - name: regcred
    envs:
      - regcred.sops.env
    type: kubernetes.io/dockerconfigjson
images:
  - name: ghcr.io/tomay0/odincards
    newTag: 2025-01-27t10-37-49
patches:
  - target:
      kind: Deployment
      name: odin
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
