namespace: odin-2
resources:
  - namespace.yaml
  - odin.k8s-sops.yaml
  - regcred.k8s-sops.yaml
  - ../../../bases/odin-2
images:
  - name: ghcr.io/tomay0/odincards
    newTag: 2025-01-27t10-37-49
patches:
  - target:
      kind: Deployment
      name: odin
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
