# Run 'talhelper genconfig -s secret.sops.yaml' to turn this into talos config

---
clusterName: talos-proxmox-cluster
talosVersion: v1.5.4
kubernetesVersion: v1.28.2
endpoint: https://192.168.100.217:6443
nodes:
  - hostname: truenas-k8s
    ipAddress: 192.168.100.217
    controlPlane: true
    installDisk: /dev/sda
allowSchedulingOnControlPlanes: true
