---
apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
spec:
  selector:
    app: website
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  namespace: website
  annotations:
    cert-manager.io/cluster-issuer: http-issuer
spec:
  rules:
  - host: izzy.kiwi
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website
            port: 
              name: http
  tls:
  - hosts:
      - izzy.kwi
    secretName: website-tls
