---
apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: website
  namespace: website
spec:
  chartRef:
    kind: OCIRepository
    name: nginx
    namespace: flux-system
  values:
    ingress:
      enabled: true
      hostname: izzy.kiwi
      tls: true
    service:
      type: ClusterIP
  interval: 5m0s
