---
apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: website
  namespace: website
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
  values:
    ingress:
      enabled: true
      hostname: izzy.kiwi
      tls: true
    service:
      type: ClusterIP
  interval: 5m0s
