apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: router
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: router
  namespace: router
  labels:
    kubernetes.io/service-name: router
addressType: IPv4
ports:
  - name: https
    appProtocol: https
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - "192.168.100.1"
    conditions:
      ready: true
