---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: global-default
value: 500
globalDefault: true
description: "This the priority class each pod will be given if none is specified"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: background-tasks
value: 100
globalDefault: false
description: "This priority class should be used for background tasks that should run at some point but are not urgent and don't mind being interrupted. e.g. Minecraft world pre-gen or Fold@Home"
