apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mc
  namespace: flux-system
spec:
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  url: oci://registry-1.docker.io/bitnamicharts/nginx
  type: oci
