apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mc
  namespace: flux-system
spec:
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  type: oci