apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-monitor
  namespace: mc-router
  labels:
    app: mc-monitor
spec:
  replicas: 1
  template:
    metadata:
      name: mc-monitor
      labels:
        app: mc-monitor
    spec:
      containers:
        - name: main
          image: itzg/mc-monitor
          env:
            - name: EXPORT_SERVERS
              value: beans.izzy.kiwi,ditchcraft.izzy.kiwi,turn-up.izzy.kiwi,hollowmere.izzy.kiwi
          args:
            - export-for-prometheus
          ports:
            - name: metrics
              containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: mc-monitor
---
apiVersion: v1
kind: Service
metadata:
  name: mc-monitor
  namespace: mc-router
  labels:
    app: mc-monitor
spec:
  selector:
    app: mc-monitor
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mc-monitor
  namespace: mc-router
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    path: /metrics
  namespaceSelector:
    matchNames:
    - mc-router
  selector:
    matchLabels:
      app: mc-monitor
