apiVersion: v1
kind: Namespace
metadata:
  name: mc-router
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-router
  namespace: mc-router
spec:
  chart:
    spec:
      chart: mc-router
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    services:
      minecraft:
        type: LoadBalancer
    resources:
      limits:
        cpu: 250m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
  interval: 5m0s
