---
apiVersion: v1
kind: Namespace
metadata:
  name: hollowmere
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hollowmere
  namespace: hollowmere
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    replicaCount: 1
    minecraftServer:
      eula: "TRUE"
      type: FABRIC
      version: 1.21.7
      memory: 2500M
      modrinth:
        projects: [worldedit, axiom, fabric-api]
        allowedVersionType: beta
    resources:
      requests: 
        memory: 2Gi
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "hollowmere.izzy.kiwi"
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
  interval: 5m0s
---
apiVersion: v1
kind: Service
metadata:
  name: moths-domain
  namespace: hollowmere
  annotations:
    mc-router.itzg.me/externalServerName: moths-domain.izzy.kiwi
spec:
  ports:
    - name: mc
      protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app.kubernetes.io/instance: hollowmere-minecraft
    app.kubernetes.io/name: minecraft
