---
apiVersion: v1
kind: Namespace
metadata:
  name: ditchcraft
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ditchcraft
  namespace: ditchcraft
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    replicaCount: 1
    minecraftServer:
      eula: "TRUE"
      type: FABRIC
      version: 1.21.5
      memory: 2500M
      difficulty: hard
      ops: boxhead_crafter,OscarE2903
      enableCommandBlock: true
      spawnProtection: 0
      viewDistance: 10
      motd: "Sweat Baby Sweat!"
      modUrls: 
        - https://github.com/gnembon/fabric-carpet/releases/download/1.4.169/fabric-carpet-1.21.5-1.4.169+v250325.jar
        - https://github.com/gnembon/carpet-extra/releases/download/1.4.169/carpet-extra-1.21.5-1.4.169.jar
      modrinth:
        projects: [otterlib, fabric-api, better-stats, geyser, tcdcommons, lithium, ferrite-core, plasmo-voice, carpet-tis-addition, floodgate, sit!, servux, inventory-sorting, simple-voice-chat, cloth-config, dynmap] # carpet-bot-restriction, carpet and carpet-extra have been installed manually
        allowedVersionType: beta
      extraPorts:
        - name: bedrock
          containerPort: 19132
          protocol: UDP
          service:
            type: LoadBalancer
            port: 19132
            enabled: true
            embedded: false
            externalTrafficPolicy: Local
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.100.213
        - name: dynmap
          containerPort: 8123
          protocol: TCP
          service:
            enabled: true
            embedded: false
            port: 80
          ingress:
            enabled: false
            annotations:
              cert-manager.io/cluster-issuer: http-issuer
            hosts:
              - name: ditchcraft.izzy.kiwi
                path: /
                pathType: Prefix
            tls:
              - secretName: map-tls
                hosts:
                  - ditchcraft.izzy.kiwi
    resources:
      requests: 
        memory: 3Gi
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "ditchcraft.izzy.kiwi"
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
    extraVolumes:
      - volumeMounts:
        - name: dynmap
          mountPath: /data/dynmap/renderdata/
        volumes:
          - name: dynmap
            persistantVolumeClaim:
              claimName: dynmap
  interval: 5m0s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynmap
  namespace: ditchcraft
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: longhorn-ephemeral
  accessModes:
    - ReadWriteOnce
