---
apiVersion: v1
kind: Namespace
metadata:
  name: ditchcraft
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ditchcraft
  namespace: ditchcraft
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    replicaCount: 1
    minecraftServer:
      eula: "TRUE"
      type: FABRIC
      version: 1.21.5
      memory: 2500M
      difficulty: hard
      ops: boxhead_crafter,OscarE2903
      enableCommandBlock: true
      spawnProtection: 0
      viewDistance: 10
      motd: "Sweat Baby Sweat!"
      modrinth:
        projects: [fabric-api, better-stats, geyser, tcdcommons, carpet-bot-restriction, carpet, lithium, carpet-extra, ferrite-core, plasmo-voice, carpet-tis-addition, floodgate, sit!]
        allowedVersionType: beta
      extraPorts:
        - name: bedrock
          containerPort: 19132
          protocol: UDP
          service:
            type: LoadBalancer
            port: 19132
            enabled: true
            embedded: false
            externalTrafficPolicy: Local
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.100.213
    resources:
      requests: 
        memory: 3Gi
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "ditchcraft.izzy.kiwi"
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
  interval: 5m0s
