apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby
  namespace: beans
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lobby
  template:
    metadata:
      labels:
        app: lobby
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        runAsNonRoot: true
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mc
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: 2G
            - name: RCON_HOST
              value: "localhost"
            - name: TYPE
              value: "PAPER"
            - name: ENABLE_COMMAND_BLOCK
              value: "FALSE"
            - name: SPAWN_PROTECTION
              value: "0"
            - name: VIEW_DISTANCE
              value: "6"
            - name: SYNC_CHUNK_WRITES
              value: "FALSE"
            - name: GUI
              value: "FALSE"
          resources:
            requests:
              cpu: 200m
              memory: 2500M
            limits:
              cpu: 1500m
              memory: 3000M
          livenessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            exec:
              command:
                - mc-health
            enabled: false
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lobby
        - name: tmp
          emptyDir: {}
