apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workflow-test
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      requeueAfterSeconds: 2700
      github:
        owner: Izzy-Irvine
        repo: workflow-test
  template:
    metadata:
      name: 'workflow-test-pr{{.number}}'
      namespace: workflow-test
    spec:
      source:
        repoURL: 'git@github.com:ant-colony-flat/k8s.git'
        path: argocd/workflow-test
        kustomize:
          nameSuffix: '-pr{{.number}}'
          commonLabels:
            app.kubernetes.io/instance: 'pr{{.number}}'
          images:
          - 'workflow-test=ghcr.io/izzy-irvine/workflow-test:{{head_sha}}'  
      project: workflow-test
      destination:
        server: https://kubernetes.default.svc
        namespace: workflow-test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

