---
apiVersion: v1
kind: Namespace
metadata:
  name: berrycraft
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: berrycraft
  namespace: berrycraft
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: mc
        namespace: default
  values:
    image:
      tag: java21
    minecraftServer:
      eula: "TRUE"
      type: PAPER
      version: 1.20.5
      difficulty: hard
      spawnProtection: 0
      motd: Be gay, do crime, don't be a dick
      memory: 1500M
      ops: boxhead_crafter,mazerinth
      enableCommandBlock: true
    resources:
      requests: 
        memory: 2Gi
    serviceAnnotations:
      "mc-router.itzg.me/externalServerName": "berrycraft.uwu.co.nz"
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
    extraPorts:
    - name: map
      containerPort: 8123
      protocol: TCP
      service:
        enabled: true
        port: 8123
      ingress:
        ingressClassName: nginx
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: http-issuer
        hosts:
          - name: berrycraft.uwu.co.nz
            path: /
        tls:
          - secretName: map-tls
            hosts:
              - berrycraft.uwu.co.nz
  interval: 5m0s
