apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-steamcmd
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-palworld
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 20Gi
