---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab-operator
  namespace: gitlab-system
spec:
  interval: 5m0s
  url: https://gitlab.com/api/v4/projects/18899486/packages/helm/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-operator
  namespace: gitlab-system
spec:
  chart:
    spec:
      chart: gitlab-operator
      sourceRef:
        kind: HelmRepository
        name: gitlab-operator
  interval: 5m0s
---
apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "6.0.2" # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.8.1/CHART_VERSIONS
    values:
      nginx-ingress:
        enabled: false
      global:
        hosts:
          domain: gitlab.izzy.kiwi
        ingress:
          configureCertmanager: true
      certmanager-issuer:
        email: isaac564465@gmail.com