---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab-operator
  namespace: gitlab-system
spec:
  interval: 5m0s
  url: https://gitlab.com/api/v4/projects/18899486/packages/helm/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-operator
  namespace: gitlab-system
spec:
  chart:
    spec:
      chart: gitlab-operator
      sourceRef:
        kind: HelmRepository
        name: gitlab-operator
