apiVersion: v1
kind: Secret
metadata:
    name: ca-secret
    namespace: default
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:oaY83eiPNBv1K4wwXw71CPrkCHPH7vTTE9DJUQQhewYcZt5OcrX/h9E2iu4/dOJ2XIjTP8aBG1/wBG4fEdrLQUv5t2uD8FzQ8nZJXKngJWwLBlMT1N1nJN7TlB/cT1rYUYEtYYYEpHjnS+ec6SBR1d5UIdO/CCsb3FIy5g2rkleBfoWvYfsvBMkhle4cZ8rvp3j6ev60KlX/yFgGptecCepL4obZ/u9/ZTZfVLEbqsAqqk4Dq4uHRW1Xhg6BCV9AsjCMHMaXNrO3BHYBrubNGh30y1DBfI4CoYOw6px2uZcnRZhsFZE3hKnD9vXDXJ9opAf5nqejJiRZo7ad+KOC2HWv63+5pFjhM/nYvb3PJTD4jf9QTN1dTiTTv5SEC38zjanML811ynR+sVKskdDoTXYMT5+riw01zTBDzPyCJmhEGcBmDriLGD/L133JBH9idzE0pZsepPspkDWXqZ+FH2EKeSFhPwvmukXJUEPfcP2R5kL4PFp0vzRyPI3/eeWnx1NGn2yXw+MYE1nCWu1BwdMv7EYDz/AVSA1xF4uwSY2WMxZG5BQ/DCO8mI98WTq3v/33D0c3xpDk0h5lhh/ngC8b4ZlbC71wa56SkV1f4075A6n77jJQcRXwZ84FHiA1e3iqq+BEGSNVqVnY1spg3eOPMX27cQ/yQr1DksdLbPwfKlh7D7ko/8mQU2lBm3vXBk5PHyC6tgb9/p243FSbBi1hpclWbVQaqTi4h8Omzikm6BmITWDQhlzDX7kAdVT3z96aFfui8iYxVbNEVi02mDmPplIhw92oCGOfoqH2YBETIAoS86EeBTuqbXWqy7MXtJPhEJHtZ0d7av5mR/C8jJMD+Q14bkNku1Xe3gJf8rWSNLQEBQCCFLZGOfomR0sWkJx4kYDwW157iPEY+MhGSnFJV7jCAqEybJzm0AQghCHXvw3ZPXfhxSJyhjNoZL3aGxTKopWUyCyEnjMKDgz7QymNS5Mi+RFXfNuG1KFvQheKauWysxgkefF4a/+ZnZvU5JZgjA5VMFNJ07N4gcQz/Kk0lpsubdjwqjxvxOBl69Pz8EIfvY/JTtdqUwvcFdXRBcvjFtz0keA6EQMWzVit6PkULfM6vxhtNg2OW2itpme03Grg4lGqXq/mxobm+iWSbrkHDOb9clUoigR+ck63N9w3ODBlRQ3SSciDOa3QIBgSKyu9PG7pRVA+iQsMdH4g99GfmZvgkz/KvFVusObzbIPsAx+/m4VhRjNbZdin8+juEyXBWBS6uzVcPv2rzbw3B8L3rum5yeKSyMBPkszmEa/9jDcfHAkW6B2jHdt9lVRr5VUWUVoLDFjPA5new0+baB2aoCApC8MCkH+pxmLipwJJAdfVOUk83RxyQClwEGMkXwdXwmu9iOW0Obptd0R3c7tpLtevurh1++VtxhaqxpcdTDBn2BdMt84QeyNr+dMqUe5MKXJKKNoPFiXgbr86YEgsqLfrDc/BYaRwHWnvJBDKsX10pzFT9clVM9mHNiLwWOtMg+SglYKNtiYBhX/X2eDRdxrbDwUNUUvbpQ9+cWPoq0ENO1cthgwCRCXpKZbT9/le3Ph9AtGLY0ZSdgXD0cv6R/VVHH8hnd+tN53N9D2Q5BO6a37A6GpIgjw7Skr6WND3My8Lkdcs13PslzvCpVpxPf7dD5EYdCyemmBk0yp8rj2pcr1Y2UJU6M5dtzlURAhW5wqQUsw9ymzn1S17o7e/9Jc6fxHEFWpSPmjpaFAEhKElrfX6Zdz+qexFqr3UoV9EB/0lvZOM0dnbyDysZsh8mIyCDCUOg6o9Ym+aa3Lw44ZvK6ucYHIuUK2luYycxRTnQ3utcpmj5BaeOszeVf/b0rQUfC1N12ikv7Fwe5rLbDePGkw7tf4YQOLBtUYdeOvbdnWyx+fX94TNhodJ8COJmucCURAQ7eXXOnZ3NtQ2+m7jAyW021cWjbG5/VARXxPb4CTEvAdQKTn/P9mZJWZYiVK6hRsmFeqgS5bRZd502ZsfFhLZxSp3Tv7ThMKfXEV25rC9J+hPJIEucFBunXRH1qGCiBFlaSW0X1Ae6f7AP5JrWbPMOs/XH99s7gcc6ZorNIRxoEiep7cQiZorvJLxJ/KeYlL27NnmPu5pntaaOJD2jptxmjtr1polZ5HYP9MB3hR7xKJbWnpYTq5eSgMBZ42OSCddpAcG/riNdJJcZ1ENu/IDqjVFk667wT8b/dvbgyPe3ga/otQRuXY=,iv:ksppPirQhBDZg6lTvk8XVVrSm/L6S1sLewuBrJnBejw=,tag:CJFb7la74IZud2xPZLli1w==,type:str]
# To create CA cert:
# openssl req -new -key ca.key -nodes -out ca.csr -sha256 -subj '/CN=izzy CA'
# openssl x509 -signkey ca.key -days 3650 -req -in ca.csr -out ca.crt -sha256
# To generate user CSR:
# openssl req -new -newkey rsa:4096 -keyout izzy.key -out izzy.csr -nodes -subj '/CN=izzy'
# or:
# openssl req -key izzy.key -new -out izzy.csr -nodes -subj '/CN=izzy'
# To sign user CSR:
# openssl x509 -req -days 365 -in izzy.csr -CA ca.crt -CAkey ca.key -out izzy.crt -set_serial 01 -sha256
# User to package cert for browser:
# openssl pkcs12 -export -out izzy.pfx -inkey izzy.key -in izzy.crt -certfile ca.crt
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eHJWVjlJQkx4Y0hLQTMy
            ZnFlWWliVmFjeXN3NDR3aGRCYXJDZXZRYmlRCkFTMXMvUVJ3RzZwWGEzMGtselJN
            WEhBVzNRZjlVQ0l5SW9xcW1RaC9rb2sKLS0tIFdnTmk0L1VxMFcySFpveXRKV1RE
            dTBXV01kcFZrU0V2VE5ZQVlTd3pNbGMKj+GYttRclnQdnTISEhV6XHv7LjxnG1Me
            zbcd3oxQp+4wJeqcReg99FEEgLMabwUbhIAEj7I9VCLbIfE34nS5uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T10:16:56Z"
    mac: ENC[AES256_GCM,data:ZBfnl1HO3qeMazhK/+/ljYEhvScyDKv0/XEW5G69QuJg0T2DpOYUw1YL/XmyEKvt+gJ/K3RsQBmci4OEc1naJjOompAO3736289oL9j7XfSGKo27SoLUm7pswm3H1tb/yiZyaQfKjbmaoXWMhVvMrjw0pE3KhS1Yo9IPzs0h1e8=,iv:ycCYjGN7d1ay+bCx6KHCHjj1TdRj4YMZ2dWYbQP5ZFs=,tag:yOa8PSTkC89PLvSZC1RP5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
