# This depends on ingress release. If deploying from scratch, remove this, deploy, add it back, deploy. 
# I feel like Flux has a way to fix this but I don't know it
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: ingress
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 5m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace