apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: loki
    namespace: k8s-monitoring
stringData:
    username: ENC[AES256_GCM,data:vGvm+YoNiA==,iv:qpfdH+y2rQlqA941gL2uFU6hyg86JbEzIZ+x/5DRc+0=,tag:nHf+avZxI95zGD7kllXPUw==,type:str]
    password: ENC[AES256_GCM,data:eO6yIojlaG+S4E4UbQCOqdPm6lW+29sN9M9IC66TApzYTGlUdLM8/K/8FKz41BPHM+F/MuVxn52AtVFk9NOYqBHfXFUORq+TAPtXCDztl3Ziyhp4E58VRghGqj3r4nWql4EOD50uQN9471EHKIqfk26MdgI2GwnipoZZNdYKUE4vZcZuiwsdEsK+3lGa9uvEO9tLVnJ22lSho9qXoXY9qoVxXJtDjvix/7AzBQ==,iv:hB6+IpXgFjWcJhniGcO4JqAKhgCwsKVB0OED+URVGTA=,tag:deqJJA5YlJPjUmRzbg0siQ==,type:str]
sops:
    age:
        - recipient: age1lyeweegkthnfzggpruszm3ru80mrm5zy6w6rnkux0r6apr42cfpssnp3p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRzkyaHhyQ1FUN3JkejZ5
            bWJkU2lMSlRsbUo2ajNJNkorN0tsS3crZGpBCm1jRUZ1SSszSlB0YlI5dGxNcC82
            K3RkbzhKNVBxR2kxaHV5cU0rVUtYRjQKLS0tIEdPSHh3dVFzMGR5VmdYd3dmcDV2
            WVZZYzdEbkQ2d0lLY2pzZGNyOWtoWGsKIdQioGc+bBQj4eWYBs4qgvWthsLlGQAZ
            CFyVb9F3YZyREjbigTi5Lflrsj0yoGFtpAPG3X8kXWgIbBZN3Sf5tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T11:14:55Z"
    mac: ENC[AES256_GCM,data:x4Thbil2ljV+T6Uen8HBJyEzsmtgb/hpH3x9OCYEFZxUvO41Io5HbB52rVBu0oCDJ/MHG7u1JR/SwC32hLyWaYw5SqCAuk3Zac3tXXGLr6iH31r4mLqqdcpj+EImrJDQVZRtqZ4d0mPLZAeL8WgHv/RnrC8tiplcSyQiAK5Geio=,iv:gnpU0x/ajSaWUQaAoYXxzJb3LvH9Bhw93qmssyW4bl8=,tag:02CP5wi+huFPe3zydtZaag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2