# TODO: get working with grafana cloud then migrate to local
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: k8s-monitoring
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: k8s-monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    cluster:
      name: clowder
    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-41-prod-au-southeast-1.grafana.net./api/prom/push
        auth:
          type: basic
        secret:
          create: false
          name: prom
      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-026.grafana.net./loki/api/v1/push
        auth:
          type: basic
        secret:
          create: false
          name: loki
    clusterMetrics:
      enabled: true
    prometheusOperatorObjects:
      enabled: true
    clusterEvents:
      enabled: true
    nodeLogs:
      enabled: false
    podLogs:
      enabled: true
    integrations:
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-singleton
                - alloy-logs
    alloy-metrics:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-logs:
      enabled: true
