# TODO: get working with grafana cloud then migrate to local
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: k8s-monitoring
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: k8s-monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    cluster:
      name: clowder
    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-41-prod-au-southeast-1.grafana.net./api/prom/push
        auth:
          type: basic
          username: "2673599"
          passwordKey: access-token
        secret:
          create: false
          name: k8s-monitoring
          namespace: k8s-monitoring
      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-026.grafana.net./loki/api/v1/push
        auth:
          type: basic
          username: "1332476"
          passwordKey: access-token
        secret:
          create: false
          name: k8s-monitoring
          namespace: k8s-monitoring
      - name: gc-otlp-endpoint
        type: otlp
        url: https://otlp-gateway-prod-au-southeast-1.grafana.net./otlp
        protocol: http
        auth:
          type: basic
          username: "1374682"
          passwordKey: access-token
        secret:
          create: false
          name: k8s-monitoring
          namespace: k8s-monitoring
        metrics:
          enabled: true
        logs:
          enabled: true
        traces:
          enabled: true
    clusterMetrics:
      enabled: true
      opencost:
        enabled: true
        metricsSource: grafana-cloud-metrics
        opencost:
          exporter:
            defaultClusterId: clowder
          prometheus:
            existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
            external:
              url: https://prometheus-prod-41-prod-au-southeast-1.grafana.net./api/prom
      kepler:
        enabled: true
    prometheusOperatorObjects:
      enabled: true
    clusterEvents:
      enabled: true
    nodeLogs:
      enabled: true
    podLogs:
      enabled: true
    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
        zipkin:
          enabled: true
          port: 9411
    alloy-metrics:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: clowder
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
      remoteConfig:
        enabled: true
        url: https://fleet-management-prod-017.grafana.net
        auth:
          type: basic
          username: "1374682"
          passwordKey: access-token
        secret:
          create: false
          name: k8s-monitoring
          namespace: k8s-monitoring
    alloy-singleton:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: clowder
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
      remoteConfig:
        enabled: true
        url: https://fleet-management-prod-017.grafana.net
        auth:
          type: basic
          username: "1374682"
          passwordKey: access-token
        secret:
          create: false
          name: k8s-monitoring
          namespace: k8s-monitoring
    alloy-logs:
      enabled: true
      alloy:
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-logs-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: clowder
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
      remoteConfig:
        enabled: true
        url: https://fleet-management-prod-017.grafana.net
        auth:
          type: basic
          username: "1374682"
          passwordKey: access-token
        secret:
          create: false
          name: k8s-monitoring
          namespace: k8s-monitoring
    alloy-receiver:
      enabled: true
      alloy:
        extraPorts:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: zipkin
            port: 9411
            targetPort: 9411
            protocol: TCP
        extraEnv:
          - name: GCLOUD_RW_API_KEY
            valueFrom:
              secretKeyRef:
                name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
                key: password
          - name: CLUSTER_NAME
            value: clowder
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: GCLOUD_FM_COLLECTOR_ID
            value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
      remoteConfig:
        enabled: true
        url: https://fleet-management-prod-017.grafana.net
        auth:
          type: basic
          username: "1374682"
          passwordKey: access-token
        secret:
          create: false
          name: k8s-monitoring
          namespace: k8s-monitoring
