apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-jam-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-jam-runner
  template:
    metadata:
      labels:
        app: game-jam-runner
    spec:
      initContainers:
        - name: config
          image: ghcr.io/izzy-irvine/gha-runner
          command: ["./config-wrapper.sh"]
          volumeMounts:
            - name: config
              mountPath: /home/runner/.credentials
              subPath: .credentials
            - name: config
              mountPath: /home/runner/.credentials_migrated
              subPath: .credentials_migrated
            - name: config
              mountPath: /home/runner/.runner
              subPath: .runner
          env:
            - name: GHA_URL
              value: ReplaceMe # Set me with a patch
            - name: GHA_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: runner-secret # create me with a secret generator
      containers:
        - name: runner
          image: ghcr.io/izzy-irvine/gha-runner
          command: ['./run.sh']
          volumeMounts:
            - name: config
              mountPath: /home/runner/.credentials
              subPath: .credentials
            - name: config
              mountPath: /home/runner/.credentials_migrated
              subPath: .credentials_migrated
            - name: config
              mountPath: /home/runner/.runner
              subPath: .runner
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: runner-config
