apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-jam-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-jam-runner
  template:
    metadata:
      labels:
        app: game-jam-runner
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      initContainers:
        - name: config
          image: ghcr.io/izzy-irvine/gha-runner
          command:
            - bash
            - -c
            - ./config.sh --unattended --replace --name runner --url $GHA_URL --token $GHA_TOKEN
          volumeMounts:
            - name: config
              mountPath: /home/runner/.credentials
              subPath: .credentials
            - name: config
              mountPath: /home/runner/.credentials_migrated
              subPath: .credentials_migrated
            - name: config
              mountPath: /home/runner/.runner
              subPath: .runner
          env:
            - name: GHA_URL
              value: ReplaceMe # Set me with a patch
            - name: GHA_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: runner-token # create me with a secret generator
      containers:
        - name: runner
          image: ghcr.io/izzy-irvine/gha-runner
          command: ['./run.sh']
          volumeMounts:
            - name: config
              mountPath: /home/runner/.credentials
              subPath: .credentials
            - name: config
              mountPath: /home/runner/.credentials_migrated
              subPath: .credentials_migrated
            - name: config
              mountPath: /home/runner/.runner
              subPath: .runner
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: runner-config
