---
apiVersion: v1
kind: Namespace
metadata:
  name: unturned
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unturned
  namespace: unturned
spec:
  selector:
    matchLabels:
      app: unturned
  replicas: 0
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: unturned
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: untunred
      initContainers:
        - name: steamcmd
          image: steamcmd/steamcmd:alpine
          command:
            - "steamcmd"
            - "+force_install_dir"
            - "/data"
            - "+login"
            - "anonymous"
            - "+app_update"
            - "1110390"
            - "+quit"
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
      - name: unturned
        image: steamcmd/steamcmd
        command:
          - "./Unturned_Headless.x86_64"
          - "-batchmode"
          - "-nographics"
        workingDir: /data
        env:
          - name: LD_LIBRARY_PATH
            value: /data/linux64
          - name: TERM
            value: xterm
        resources:
          limits:
            memory: "3000Mi"
            cpu: "2000m"
        volumeMounts:
          - mountPath: /data
            name: data
        # ports:
        # - containerPort: 27015
        #   protocol: TCP
        # - containerPort: 27015
        #   protocol: UDP
        # - containerPort: 27016
        #   protocol: TCP
        # - containerPort: 27016
        #   protocol: UDP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: untunred
  namespace: unturned
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
